server:
  port: 8003
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-vod
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  profiles:
    active: dev
#aliyun:
#  vod:
#    file:
#      keyid: 'LTAI4FvvVEWiTJ3GNJJqJnk7'
#      keysecret: '9st82dv7EvFk9mTjYO1XXbM632fRbG'
